### ISSUE TITLE
Track ecommerce product and category views

### ISSUE THREAD

**Issue by mattab** [PiwikPRO/3rdparty-woocommerce#1]
The goal of this issue is to add support for Ecommerce View tracking of product views and category pageviews. See: https://wordpress.org/support/topic/add-additional-code-to-track-product-page-viewsconversions

Documentation: http://piwik.org/docs/ecommerce-analytics/#tracking-product-page-views-category-page-views-optional

**Comment by mattab** [comment]
FYI It was requested by users in https://github.com/piwik/piwik/issues/6975 - high value enhancement :+1:

**Comment by quba** [comment]
@vox3r please sent me update after closing this one

**Comment by vox3r** [comment]
done.
