### ISSUE TITLE
done like this - done best

### ISSUE THREAD

**Issue by Tobias-Conrad** [PiwikPRO/3rdparty-woocommerce#12]
sorry, but this is the sky:
http://codecanyon.net/item/actionable-google-analytics/9899552

**Comment by sebastianpiskorski** [comment]
@Tobias-Conrad: Sorry but I don't get it. Is it stolen or something?

**Comment by Tobias-Conrad** [comment]
This is what Google analytics brings to you.
No need to use piwik.
