### ISSUE TITLE
the plugin has got no valid header

### ISSUE THREAD

**Issue by Tobias-Conrad** [PiwikPRO/3rdparty-woocommerce#3]
wp-admin/plugins.php?action=activate&plugin=3rdparty-woocommerce-2.1.0%2Fincludes%2Fclass-wc-piwik.php&_wpnonce=7efba3f7cc

**Comment by Tobias-Conrad** [comment]
i installed the master version of today on WP 4.1

**Comment by quba** [comment]
@vox3r could you check that?

**Comment by Tobias-Conrad** [comment]
check what nothing was changed?
when are the 2.1 version is ready with woo product cat. integration?

**Comment by mgazdzik** [comment]
@vox3r - awaiting for release

**Comment by quba** [comment]
@vox3r could you release the new version on the Wordpress market?

**Comment by kaz231** [comment]
Plugin was deployed to WP market.

**Comment by mattab** [comment]
Nice work guys :+1:

**Comment by Tobias-Conrad** [comment]
Das Plugin hat keinen validen Header.
invalide header.
i deinstalled plugin and installed again.
whats up?
