### ISSUE TITLE
still no valid header

### ISSUE THREAD

**Issue by Tobias-Conrad** [PiwikPRO/3rdparty-woocommerce#6]
check it
i deinstalled plugin and installed again.
still no valid header
whats up?

**Comment by kaz231** [comment]
Hi @Tobias-Conrad , could you send me a woocommerce-piwik-integration.php file (it's inside of the plugin's directory) ? I tried to reproduce this issue locally, but I achieved it only by manual modification of header of woocommerce-piwik-integration.php file.

**Comment by Tobias-Conrad** [comment]
<?php
/**

Plugin Name: WooCommerce Piwik integration
Plugin URI: http://wordpress.org/plugins/woocommerce-piwik-integration/
Description: Allows Piwik and Piwik PRO tracking code to be inserted into WooCommerce store pages.
Author: Piwik PRO
Author URI: http://www.piwik.pro
Version: 2.1.0
*/

function wc_piwik_add_integration( $integrations ) {
	global $woocommerce;

	if ( is_object( $woocommerce ) && version_compare( $woocommerce->version, '2.1-beta-1', '>=' ) ) {
		include_once( 'includes/class-wc-piwik.php' );
		$integrations[] = 'WC_Piwik';
	}

	return $integrations;
}

add_filter( 'woocommerce_integrations', 'wc_piwik_add_integration' );

**Comment by quba** [comment]
@Tobias-Conrad we still cannot reproduce the issue. What is the current status on your end?

**Comment by Tobias-Conrad** [comment]
working
