### ISSUE TITLE
nothings works - no ecommerce success tracking

### ISSUE THREAD

**Issue by Tobias-Conrad** [PiwikPRO/3rdparty-woocommerce#9]
only normal tracking through the WP-Piwik plugin
abbandoned carts tracking
but not succesfull carts tracking
no changelog on wordpress.org to check if new features are working

make it good please

i use woocommerce and i like to use your plugin.

**Comment by Tobias-Conrad** [comment]
Warenkorb | Santegra Heilpflanzen Infothek (Cart)
https://www.santegra-international.com/warenkorb/

Kasse | Santegra Heilpflanzen Infothek (Checkout)
https://www.santegra-international.com/checkout/

Bestellung prüfen → Bezahlen | Santegra Heilpflanzen Infothek (confirm)
https://www.santegra-international.com/bestellung_pruefen_bezahlen/

and no more further tracking on a succesfull order

**Comment by Tobias-Conrad** [comment]
product views, category views:
haha where is it? do you here me laughing?
Where should it be?
here (cat.) http://awesomescreenshot.com/07e4kmc4a2
or
here (prod.) http://awesomescreenshot.com/0484kmc067

**Comment by Tobias-Conrad** [comment]
on santegra-international.com i have test product and a testpayment so you can check the WOO tracking on a live system.

**Comment by quba** [comment]
Checking successful orders will be impossible without having access to Piwik instance. @kaz231 for sure tested it recently, so I think it's an edge case that we need to check. @kaz231 or @vox3r please double check it (maybe using this live example).

**Comment by Tobias-Conrad** [comment]
hey quba howto sent you access to piwik?

**Comment by quba** [comment]
Please send the credentials to kuba[at]piwik.pro

Thanks.

**Comment by Tobias-Conrad** [comment]
done. thanks for helping...

**Comment by kaz231** [comment]
Hi @Tobias-Conrad , the bug will be fixed in the newest Piwik version - 2.12
